# k-Means Clustering

Today, we're going to implement our own k-Means clustering function. We will use this function, and another clustering model from scikit-learn, to replicate the results of Ahlquist & Breunig (2012). The data for this paper has been provided.

## Imports

We'll need _at least_ the following modules. You may use additional modules if they are helpful.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## First, let's implement k-Means

Remember, the k-Means algorithm consists of the following steps:

1. Randomly initialize k points within the range of your data.
    * Hint: you can do this either by randomly sampling points from within the bounds of all the variables you'll be clustering _or_ you can randomly sample values from your actual data.
2. Compute the distance from every cluster to every point in your data.
3. Find the nearest cluster to every point.
4. For all the points in each cluster, compute their mean value.
5. Use the newly-found mean values as your new cluster centroids.
6. Repeat X times (usually 10-20).

## A note on notation

* `data` is your dataset - an (n x p) numpy array
* `centroids` are the means of each cluster, a (k x p) numpy array
* `n` is the number of datapoints in your data
* `k` is the number of clusters
* `p` is the number of variables per data point
* `x` and `y` represent two singular datapoints
* `dists` represents an (n x k) numpy array of distances
* `iterations` is the number of iterations to run the model

## Problem 1

Complete the below functions. The red "docstrings" at the top of each function tells you precisely what each function should input and output. It also describes what the function should accomplish.

In [189]:
def euclidean_distance(x,y):
    """
    This function computes sqrt((x-y)^2) for two points, x and y.
    Inputs
        x: a (1 x p) numpy array
        y: a (1 x p) numpy array
    Outputs
        A single numerical value, the distance between x and y.
    """
    distance = np.sqrt(np.sum((x - y)**2))

    return distance

def get_distances(data, centroids):
    """
    This function computes the distances from every point to every
    cluster centroid.
    Inputs
        data: an (n x p) numpy array of data points
        centroids: a (k x p) numpy array of cluster centers
    Outputs
        An (n x k) numpy array of distances from points to clusters.
    """
    distance_matrix = np.empty((data.shape[0], centroids.shape[0]))
    
    for i in range(0,data.shape[0]):
        for j in range(0,centroids.shape[0]):
            distance_matrix[i,j] = euclidean_distance(data[i], centroids[j])

    return distance_matrix
    
def get_clusters(dists):
    """
    This function computes the cluster assignment for all points.
    Inputs
        dists: an (n x k) numpy array
    Outputs
        An (n x 1) numpy array of datapoints by cluster assignments.
    """
    cluster_assignments = np.argmin(dists, axis = 1)
    ## Hint: np.argmin will help...
    
    return cluster_assignments

def compute_new_centroids(data, cluster_assignments):
    """
    This function computes the new centroids (means) for each cluster.
    Inputs
        data: an (n x p) numpy array of your data points
        cluster_assignments: an (n x 1) numpy array giving the nearest 
            cluster to each point in your dataset.
    Outputs
        A (k x p) numpy array of cluster centroids (means).
    """
    uniqueClusterIndexes = np.unique(cluster_assignments)
    sz = uniqueClusterIndexes.size
    centroids = np.repeat([np.NaN,np.NaN], sz, axis = 0).reshape(sz,2)
    for i, idx in enumerate(uniqueClusterIndexes):
        currentDataIndexes = np.argwhere(cluster_assignments == idx)
        sh = currentDataIndexes.shape[0]
        if sh > 0:
            x = np.mean(data[currentDataIndexes.reshape(sh,)][:,0])
            y = np.mean(data[currentDataIndexes.reshape(sh,)][:,1])
            centroids[i] = [x,y]  

    return centroids



def kmeans(data, k=3, iterations=10):
    """
    Runs the k-Means algorithm.
    Inputs
        data: an (n x p) numpy array representing your data
        k: the number of clusters to estimate (1 < k <= n)
        iterations: the number of cycles to run the algorithm
    Outputs
        A tuple of (cluster_assignments, centroids) where:
         * cluster_assignments is a numpy array of (n x 1)
         * centroids is a numpy array of (k x p)
    """
    
    ## Initialize k randomly-selected points for centroids.
    ## You might find np.random.choice to help here.
    
    
    
    #centroids = data[np.random.choice(data.shape[0], k, replace=False)].copy()
    centroids = np.random.normal(loc=5, scale=2, size=(k,data.shape[1]))    
    print("Initial Centroids:", centroids)
    
    ## Loop for _iterations_ times.
    for ii in range(iterations):        
        
        ## 1. Compute distances between data and centroids
        distances = get_distances(data, centroids)
        
        ## 2. Get cluster assignment for each datapoint
        cluster_assignments = get_clusters(distances)       
        
        ## 3. Compute new cluster centroids
        tmpClusters = compute_new_centroids(data, cluster_assignments)
        for i, newCentroidIndex in enumerate(np.unique(cluster_assignments)):
            centroids[newCentroidIndex] = tmpClusters[i]        
        
    return (cluster_assignments, centroids)

In [196]:
data_input = np.array([[3.7, 2.4], [3.0, 2.5], [3.4, 3.3], [3.8,3.0],[2.8,3.3],[5.0, 10.3],[5.5,10.9],[4.5,11.3],[10.2,7.5], [11.2,8.6]])
print([np.mean(data[:5, 0]), np.mean(data[:5, 1])])
print([np.mean(data[5:8, 0]), np.mean(data[5:8, 1])])
print([np.mean(data[8:10, 0]), np.mean(data[8:10, 1])])
kmeans(data_input, 3, 1000)

[3.34, 2.9]
[5.0, 10.833333333333334]
[10.7, 8.05]
Initial Centroids: [[5.92226318 8.54944788]
 [3.6768688  4.51165808]
 [5.71814875 5.6937139 ]]


(array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0]), array([[7.28      , 9.72      ],
        [3.34      , 2.9       ],
        [5.71814875, 5.6937139 ]]))

In [152]:
data = np.array([[3.7, 2.4], [3.0, 2.5], [3.4, 3.3], [3.8,3.0],[2.8,3.3],[5.0, 10.3],[5.5,10.9],[4.5,11.3],[10.2,7.5], [11.2,8.6]])
print(data)
print([np.mean(data[:5, 0]), np.mean(data[:5, 1])])
print([np.mean(data[5:8, 0]), np.mean(data[5:8, 1])])
print([np.mean(data[8:10, 0]), np.mean(data[8:10, 1])])
data[8:10, 0]
#centroids = np.array([[2.0, 4.0],[4.0, 12.0], [10.0, 9.0]])
#distances = get_distances(data, centroids)
#print(distances)
#cluster_assignments = get_clusters(distances)
#compute_new_centroids(data, cluster_assignments)



[[ 3.7  2.4]
 [ 3.   2.5]
 [ 3.4  3.3]
 [ 3.8  3. ]
 [ 2.8  3.3]
 [ 5.  10.3]
 [ 5.5 10.9]
 [ 4.5 11.3]
 [10.2  7.5]
 [11.2  8.6]]
[3.34, 2.9]
[5.0, 10.833333333333334]


array([10.2, 11.2])

In [120]:
#data[np.random.choice(10, 3, replace=False)].copy().shape
np.random.choice(50, 2, replace=False)
np.random.normal(loc=5, scale=10, size=(3,2))

array([[ 7.65765602, -8.93976053],
       [-8.20947713, -0.69803999],
       [13.0010013 , 12.02775926]])

In [73]:
data = np.array([[3.7, 2.4], [3.0, 2.5], [3.4, 3.3], [3.8,3.0],[2.8,3.3],[5.0, 10.3],[5.5,10.9],[4.5,11.3],[10.2,7.5], [11.2,8.6]])
print(data)
centroids = np.array([[2.0, 4.0],[4.0, 12.0], [10.0, 9.0]])
distances = get_distances(data, centroids)
clusterAssignments = get_clusters(distances)
print(clusterAssignments)
uniqueClusterIndexes = np.unique(clusterAssignments)
sz = uniqueClusterIndexes.size
newCentroids = np.repeat([np.NaN,np.NaN], sz, axis = 0).reshape(sz,2)


print(uniqueClusterIndexes)
for i, idx in enumerate(uniqueClusterIndexes):    
    currentDataIndexes = np.argwhere(clusterAssignments==idx)
    sh = currentDataIndexes.shape[0]
    if sh > 0:
        x = np.mean(data[currentDataIndexes.reshape(sh,)][:,0])
        y = np.mean(data[currentDataIndexes.reshape(sh,)][:,1])
        newCentroids[i] = [x,y]
        
print(newCentroids.shape)
        
    

 

[[ 3.7  2.4]
 [ 3.   2.5]
 [ 3.4  3.3]
 [ 3.8  3. ]
 [ 2.8  3.3]
 [ 5.  10.3]
 [ 5.5 10.9]
 [ 4.5 11.3]
 [10.2  7.5]
 [11.2  8.6]]
[0 0 0 0 0 1 1 1 2 2]
[0 1 2]
(3, 2)


In [ ]:
arr = np.array([[8, 13,  5,  0],[ 0,  2,  5,  3],[10,  7, 15, 15],[ 3, 11,  4, 12]])
print(arr)
#print("\nIndices of min element : ", np.argmin(arr, axis = 1).shape) 
rrr = np.empty((arr.shape[0], ), dtype=np.int64)
result = np.argmin(arr, axis = 1)
print(result)

print(result.reshape(4,1).shape)

## Problem 2

Let's test our kmeans function with the Iris data we've used before. I've given you a plotting function to make it easy...

In [ ]:
def plot_categories(X, Y, category):
    fig, ax = plt.subplots()
    unique_categories = np.unique(category)
    for cat in unique_categories:
        ax.plot(X[category==cat], Y[category==cat], marker='o', linestyle='', label=cat)
    return ax

Now, we will read the Iris dataset and use just the `PetalLength` and `PetalWidth` features (columns). Below, I have provided code to plot these two features.

In [ ]:
iris = pd.read_csv("iris.csv")
features = np.array(iris[["PetalLength","PetalWidth"]])
plot_categories(features[:,0], features[:,1], iris["Species"])


Finally, see how well your k-means algorithm does. First, let's use `k=3` and `iterations=1`. Compute the results and make a new plot colored by cluster assignment

In [ ]:
## Your code here...



## Problem 3

Now, increase `iterations` to 10 and plot the results. How do they compare to the true values from the Iris dataset?

## Problem 4

Just for fun, let's see what happens if we increase `k` to 6. Plot the results below.

## Problem 5

Let's replicate Ahlquist & Breunig (2012) Figure 3a. I've gotten you started (below) by loading the data and adding the "ground truth" VOC values.

In [ ]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.mixture import GaussianMixture

data = pd.read_csv("iversen.csv")
countries = ["AUS", "CAN","GBR",
            "JPN","CHE","USA",
            "AUT","BEL","DEU",
            "FRA","ITA","DNK",
            "FIN","NLD","NOR",
            "SWE","GRC", "IRL", 
            "NZL","PRT","ESP"]
VoC_class = ["LME","LME","LME",
             "CME","CME","LME",
             "CME","CME","CME",
             "NC","NC","CME",
             "CME","CME","CME",
             "CME","NC","LME",
             "LME","NC", "NC"]
VoC_color = {"CME":"red","LME":"black","NC":"green"}

voc_data = pd.DataFrame(list(zip(countries,VoC_class)), columns=["wbcode","voc"])

merged_data = pd.merge(data, voc_data, on="wbcode")
merged_data.head()

Now, let's use sklearn's `StandardScaler` to scale our variables to have 0 mean and 1 variance. You can find the documentation for this at https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html.

In [ ]:
scaler_employment = StandardScaler()
scaled_employment_data = scaler_employment.fit_transform(merged_data[["epl","cdp","cop"]])

scaler_unemployment = StandardScaler()
scaled_unemployment_data = scaler_unemployment.fit_transform(merged_data[["nurr","gb","dsj"]])


Next, we'll use sklearn's `PCA` to compute principal components that represent employment and unemployment variables. This process is described in section 4.1.1 of the paper. We stack these into an `X` matrix of size (n x 2).

In [ ]:
employment_pca = PCA(n_components=1)
employment_pca_values = employment_pca.fit_transform(scaled_employment_data)

unemployment_pca = PCA(n_components=1)
unemployment_pca_values = unemployment_pca.fit_transform(scaled_unemployment_data)

X = -np.hstack([employment_pca_values, unemployment_pca_values])

Now, use both your k-means implementation and sklearn's `GaussianMixture` to reproduce Figure 3(a) of the paper. You do not need to draw the ellipses around the clusters, just color the points by cluster like we did above. For the Gaussian Mixture model, use `covariance_type='tied'`. Also, you should use `k=5` for your k-means and `n_components=5` for the Gaussian Mixture.

## Problem 6

Now that you've estimated a Gaussian Mixture model, you will need to make predictions for each datapoint. That is, predict the cluster that every datapoint belongs to. You can use the `.predict(...)` method of your Gaussian Mixture object to do so. See the documentation if it is unclear.

## Problem 7

Plot your results for k-means and for the gaussian mixture model. You can use the same function we used for the iris data.

## Problem 8

Select a dataset of your choice (any...) and use clustering (either k-means or any of the clustering options available from [scikit-learn](https://scikit-learn.org/stable/modules/clustering.html)) to explore that dataset. Prepare to discuss your data, your clustering choices, and the results for approximately 5-10 minutes on March 24.